version: 0.2
phases:
  install:
    commands:
      - echo "install step"
  pre_build:
    commands:
      - echo "any prebuild actvities"
  build:
    commands:
      - echo Building 
      - mkdir -p output
      - chmod -R 777 output
      - docker run --rm -e REPO='https://github.com/richardjkendall/echo-api' -v $(pwd)/output:/output richardjkendall/lambda-builder
      - cd output; zip -r ../function.zip .
      - cd ..; aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://function.zip